services:
  travel-bp-api:
    container_name: travel-bp-api
    build:
      context: ./apps/api
    ports:
      - "8080:8080" # (for HTTP)
      - "8081:8081" # (for HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - "ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=TravelBookingPlatform;User Id=sa;Password=Aa@1231Bb!;TrustServerCertificate=True;"
      - "ConnectionStrings__SerilogConnection=Server=sql-server-db;Database=master;User Id=sa;Password=Aa@1231Bb!;TrustServerCertificate=True;"
    depends_on:
      sql-server-db:
        condition: service_healthy
    networks:
      - travel-network

  # Next.js Documentation Service (Production)
  travel-bp-docs:
    container_name: travel-bp-docs
    build:
      context: ./apps/docs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - travel-network
    restart: unless-stopped # Add restart policy

  # Next.js Client Application Service (NEW - Production)
  travel-bp-client:
    container_name: travel-bp-client
    build:
      context: ./apps/client
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - travel-network
    restart: unless-stopped

  # MS SQL Server Database Service
  sql-server-db:
    container_name: sql-server-db
    build:
      context: ./apps/api/docker/sql-server
    environment:
      - ACCEPT_EULA=Y
      - "MSSQL_SA_PASSWORD=Aa@1231Bb!"
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql
    networks:
      - travel-network
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-C",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Aa@1231Bb!",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

# Define a network for the services to communicate
networks:
  travel-network:
    driver: bridge

# Define a volume to persist database data across container restarts
volumes:
  sql-server-data:
    driver: local
