name: .NET Core Development Check
run-name: ${{ github.actor }} pushing changes to ${{ github.ref }}
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    name: Development Check
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "test-ci-password"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Wait for SQL Server to be ready
      run: |
        echo "Waiting for SQL Server to start..."
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "test-ci-password" -Q "SELECT 1"
        while [ $? -ne 0 ]
        do
          sleep 1
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "test-ci-password" -Q "SELECT 1"
        done
        echo "SQL Server is up and running."
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity minimal
    env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=YourTestDB;User Id=sa;Password=test-ci-password;"

