name: .NET Core Development Check
run-name: ${{ github.actor }} pushing changes to ${{ github.ref }}
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    name: Development Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./apps/api

    - name: Build
      run: dotnet build ./apps/api --no-restore

    - name: Run Multiple Unit Tests
      run: |
        dotnet test ./apps/api/tests/TravelBookingPlatform.UnitTests/TravelBookingPlatform.Hotels.UnitTests/TravelBookingPlatform.Hotels.UnitTests.csproj --no-build --verbosity minimal
        dotnet test ./apps/api/tests/TravelBookingPlatform.UnitTests/TravelBookingPlatform.Identity.UnitTests/TravelBookingPlatform.Identity.UnitTests.csproj --no-build --verbosity minimal
      env:
        ASPNETCORE_ENVIRONMENT: "MockedTesting"