name: .NET Core Development Check
run-name: ${{ github.actor }} pushing changes to ${{ github.ref }}
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    name: Development Check
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install SQL Server tools
      run: |
        echo "Installing SQL Server tools..."
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

    - name: Wait for SQL Server to be ready
      run: |
        echo "Waiting for SQL Server to start..."
        # Loop until sqlcmd is successful
        for i in {1..30}; do
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "yourStrong(!)Password" -Q "SELECT 1" && break
          echo "SQL Server not ready yet, waiting..."
          sleep 1
        done
        echo "SQL Server is up and running."

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity minimal
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost;Database=TravelBookingPlatform;Trusted_Connection=True;TrustServerCertificate=True"